# Everforest dark medium palette
set -g @thm_bg         "#2d353b"
set -g @thm_mantle     "#232a2e"
set -g @thm_crust      "#232a2e"
set -g @thm_base       "#2d353b"
set -g @thm_surface_0  "#343f44"
set -g @thm_surface_1  "#3d484d"
set -g @thm_surface_2  "#475258"
set -g @thm_surface0   "#343f44"
set -g @thm_surface1   "#3d484d"
set -g @thm_surface2   "#475258"
set -g @thm_overlay_0  "#7a8478"
set -g @thm_overlay_1  "#859289"
set -g @thm_overlay_2  "#9da9a0"
set -g @thm_overlay0   "#7a8478"
set -g @thm_overlay1   "#859289"
set -g @thm_overlay2   "#9da9a0"
set -g @thm_subtext0   "#9da9a0"
set -g @thm_subtext1   "#d3c6aa"
set -g @thm_text       "#d3c6aa"
set -g @thm_rosewater  "#d3c6aa"
set -g @thm_flamingo   "#e67e80"
set -g @thm_pink       "#d699b6"
set -g @thm_mauve      "#83c092"
set -g @thm_red        "#e67e80"
set -g @thm_maroon     "#e69875"
set -g @thm_peach      "#e69875"
set -g @thm_yellow     "#dbbc7f"
set -g @thm_green      "#a7c080"
set -g @thm_teal       "#83c092"
set -g @thm_sky        "#83c092"
set -g @thm_sapphire   "#7fbbb3"
set -g @thm_blue       "#7fbbb3"
set -g @thm_lavender   "#d699b6"
